### ISSUE TITLE
Does not compile unfortunately, alot of dependencies are missing, invalid code (non-implemented abstract classes etcetera)

### ISSUE THREAD

**Issue by cruuud** [Gota7/NitroStudio2#1]
I have spent alot of time trying to get this all to compile in Visual Studio 2019.

After installing all needed dependencies (VGAudio, NAudio, your other projects) it still does not compile, missing implementations of abstract classes, so maybe you have added an old state of your application?

There are typos in classes (IWriteable instead of IWritable, in some places correct though), so I guess it would be good to upload a compilable state, if you want others to contribute.

**Comment by Gota7** [comment]
I appreciate the interest in Nitro Studio 2, and am really sorry for the inconvenience. When rushing out the source release for NS2, I forgot to update the dependencies, and even overlooked listing one in the readme. After updating all the dependencies' online sources and testing, you should be able to get it to compile now if you download all the updated dependencies, remove and re-add all of them to the NS2 solution, then re-add project references to the projects that need them, and finally reinstalling the nuget packages required. Please tell me how this works out.

**Comment by cruuud** [comment]
Thank you for your support, I finally got it to build, but I had to download older versions of NAudio and VGAudio and Sanford.Multimedia.Mid, so you need to update your package configs to reflect the actual versions you are using.

**Comment by Gota7** [comment]
Strange, I just downloaded those sources from NuGET when reinstalling them and it worked fine.

**Comment by cruuud** [comment]
Yeah that is weird! I had to install old version from NAudio and VGAudio and only then it worked. Well, I guess the issue can be closed now, thank you for this awesome tool! =)

**Comment by AdAstra-LD** [comment]
I was having the same issue but I finally got it to compile after manually fixing pretty much every dependency to NAudio, VGAudio and Sanford.Multimedia.Midi [I created a bunch of new forks]
Now the problem is that it won't let me edit "MainWindow.cs" and I'm getting this.
![image](https://user-images.githubusercontent.com/76622070/107385520-3ee93480-6af3-11eb-8542-e90000496132.png)

Any help is much appreciated!

**Comment by Gota7** [comment]
Yeah, dependencies are weird and need to be re-added. But the secret to the UI is that it's one UI, not a bunch. The individual CS code for windows is just overrides and stuff for the window, all the actual form code is in EditorBase.cs, which is what you need to edit.

**Comment by AdAstra-LD** [comment]
Oh, I see. Thanks. I think I'm getting the hang of it.
